### PR TITLE
Fix travis so flake8 does not run on python26

### LINKED ISSUE #26: flake8 does not work in 2.6
As seen in [this failed build](https://travis-ci.org/planetarypy/pvl/jobs/210137800), ``flake8`` no longer works in python2.6 because flake8 uses an OrderedDict not present in python2.6.

To recreate:
```bash
$ virtualenv temp_env --python=`which python2.6`
$ source temp_env/bin/activate
$ pip install -r requirements.txt
$ flake8 pvl
.
.
.
    parameters = collections.OrderedDict([
AttributeError: 'module' object has no attribute 'OrderedDict'
```

### PR DESCRIPTION
**Pull request by pbvarga1**
Fixes #26

### CODE REVIEW

**Comment by pbvarga1** [comment]
Should note, I followed [this somewhat](https://github.com/epfl-scitas/spack/blob/4624f8b1944d65ff7156b98a544f523dc23758ac/.travis.yml) as a fix

**Comment by godber** [comment]
Since the `flake8` test is redundant across the python versions I think this approach is acceptable, but I will defer to @wtolson.

**Comment by pbvarga1** [comment]
@godber Another approach is to use tox but I found this to be simpler
