### ISSUE TITLE
Update pvl to multidict 6.4.4 or higher

### ISSUE THREAD

**Issue by rbeyer** [planetarypy/pvl#111]
**Describe the bug**
_pvl_ requires an ordered multi-dict type to contain the PVL structures that it parses.  The default is `pvl.collections.OrderedMultiDict` which is a custom type that _pvl_ uses.  The codebase has an experiment with a "new" ordered multi-dict type, `pvl.collections.PVLMultiDict`, based on the 3rd party _multidict_ library.  That _multidict_ library has had some API changes such that the derived code in _pvl_ no longer works with _multidict_ 6.4.4.

The solution is to patch up the _pvl_ code, primarily removing references to the `MultiDict._impl` object and `MultiDict._title()` function so that _pvl_ can function with the latest version of _multidict_.

If a user isn't explicitly using the "new" `pv.collections.PVLMultiDict` or importing `pvl.new as pvl` then they will be unaffected by this bug.

**To Reproduce**
Steps to reproduce the behavior.
Have _multidict_ 6.4.4 installed and do `make test` in the _pvl_ repo, you will see:
```
FAILED tests/test_collections.py::TestMultiDicts::test_insert - AttributeError: 'PVLMultiDict' object has no attribute '_title'
```

See also the errors from this Action run: https://github.com/planetarypy/pvl/actions/runs/15647702347/job/44087820851#step:8:418

**Expected behavior**
`make test` in the _pvl_ repo should result in no errors.
