### ISSUE TITLE
flake8 does not work in 2.6

### ISSUE THREAD

**Issue by pbvarga1** [planetarypy/pvl#26]
As seen in [this failed build](https://travis-ci.org/planetarypy/pvl/jobs/210137800), ``flake8`` no longer works in python2.6 because flake8 uses an OrderedDict not present in python2.6.

To recreate:
```bash
$ virtualenv temp_env --python=`which python2.6`
$ source temp_env/bin/activate
$ pip install -r requirements.txt
$ flake8 pvl
.
.
.
    parameters = collections.OrderedDict([
AttributeError: 'module' object has no attribute 'OrderedDict'
```
